//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMember
    {
        public int cid { get; set; }
        public string cuserid { get; set; }
        public string cpwd { get; set; }
        public string cname { get; set; }
        public string cphone { get; set; }
        public string cemail { get; set; }
        public string caddress { get; set; }
        public string cstatus { get; set; }
        public string creport { get; set; }
        public string cphotoname { get; set; }
        public string cphotopath { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<System.DateTime> cretime { get; set; }
    }
}
