//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch16.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Delivery
    {
        public int did { get; set; }
        [DisplayName("帳號")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "帳號最少4個字，最多20個字")]
        [Required(ErrorMessage = "請輸入帳號")]
        [RegularExpression(@"^.*(?=.*\d)(?=.*[a-zA-Z]).*$", ErrorMessage = "帳號須包含英文數字")]
        public string duserid { get; set; }

        [DisplayName("密碼")]
        [DataType(DataType.Password)]
        [StringLength(20, ErrorMessage = "密碼最長20個字")]
        [RegularExpression(@"^.*(?=.*\d)(?=.*[a-zA-Z]).*$", ErrorMessage = "密碼須包含英文數字")]
        [Required(ErrorMessage = "請輸入密碼")]
        public string dpwd { get; set; }

        [DisplayName("姓名")]
        [StringLength(20, ErrorMessage = "姓名最多20個字")]
        [Required(ErrorMessage = "請輸入外送員姓名")]
        public string dname { get; set; }

        [DisplayName("手機號碼")]
        [Required(ErrorMessage = "請輸入手機")]
        [RegularExpression(@"^[09][0-9]{9}", ErrorMessage = "手機為09開頭，請輸入十個數字")]
        public string dphone { get; set; }


        public string suserid { get; set; }
        public string historydel { get; set; }
    }
}
