//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch16.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Menu
    {
        public int meid { get; set; }
        public string mid { get; set; }
        public string suserid { get; set; }

        [DisplayName("餐點")]
        public string mname { get; set; }

        [DisplayName("價錢")]
        public Nullable<int> mprice { get; set; }
        public string mcid { get; set; }
        public string historymenu { get; set; }
    }
}
