//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch16.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Order
    {
        public int oid { get; set; }
        public string orderguid { get; set; }
        public string cuserid { get; set; }
        public string suserid { get; set; }
        public string duserid { get; set; }
        public string receiver { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string oway { get; set; }
        public Nullable<System.DateTime> odate { get; set; }
        public string ostatus { get; set; }

        [DisplayName("拒絕原因")]
        public string note { get; set; }
        public string isapproved { get; set; }
        public string opwd { get; set; }
    }
}
