//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch16.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class StoreMember
    {
        public int sid { get; set; }

        [DisplayName("帳號")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "帳號最少4個字，最多20個字")]
        [Required(ErrorMessage = "請輸入帳號")]
        [RegularExpression(@"^.*(?=.*\d)(?=.*[a-zA-Z]).*$", ErrorMessage = "帳號須包含英文數字")]
        public string suserid { get; set; }

        [DisplayName("密碼")]
        [DataType(DataType.Password)]
        [StringLength(20, ErrorMessage = "密碼最長20個字")]
        [RegularExpression(@"^.*(?=.*\d)(?=.*[a-zA-Z]).*$", ErrorMessage = "密碼須包含英文數字")]
        [Required(ErrorMessage = "請輸入密碼")]
        public string spwd { get; set; }

        [DisplayName("店名")]
        [StringLength(20, ErrorMessage = "店名最多20個字")]
        [Required(ErrorMessage = "請輸入店名")]
        public string sname { get; set; }

        [DisplayName("手機號碼")]
        [Required(ErrorMessage = "請輸入手機")]
        [RegularExpression(@"^[09][0-9]{9}", ErrorMessage = "手機為09開頭，請輸入十個數字")]
        public string sphone { get; set; }

        [DisplayName("信箱")]
        [StringLength(50, ErrorMessage = "信箱最多只能輸入50個字")]
        [Required(ErrorMessage = "請輸入信箱")]
        [EmailAddress]
        public string semail { get; set; }

        [DisplayName("地址")]
        [StringLength(50, ErrorMessage = "地址最多50個字")]
        [Required(ErrorMessage = "請輸入地址")]
        public string saddress { get; set; }

        [DisplayName("營業時間")]
        [StringLength(50, ErrorMessage = "營業時間最多50個字")]
        [Required(ErrorMessage = "請輸入營業時間")]
        public string shour { get; set; }


        public string cateid { get; set; }

        [DisplayName("介紹")]
        [StringLength(200, ErrorMessage = "簡介最多200個字")]
        [Required(ErrorMessage = "請輸入簡介")]
        public string sinf { get; set; }
        public string sstatus { get; set; }
        public string sreport { get; set; }
        public string sdelivery { get; set; }
        public string sphotoname { get; set; }
        public string sphotopath { get; set; }
        public string mephotoname { get; set; }
        public string mephotopath { get; set; }
        public string sopen { get; set; }
    }
}
