//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreCategory
    {
        public int sid { get; set; }
        public string suserid { get; set; }
        public string spwd { get; set; }
        public string sname { get; set; }
        public string sphone { get; set; }
        public string semail { get; set; }
        public string saddress { get; set; }
        public string shour { get; set; }
        public string sinf { get; set; }
        public string sclass { get; set; }
        public string sphotoname { get; set; }
        public string cateid { get; set; }
        public string mephotoname { get; set; }
    }
}
