//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch16.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class StoreReport
    {
        public int srid { get; set; }
        public string auserid { get; set; }
        public string suserid { get; set; }
        public string cuserid { get; set; }
        public string orderguid { get; set; }

        [DisplayName("回報內容")]
        public string srcontent { get; set; }
        public string srreply { get; set; }
        public string srstatus { get; set; }
        public Nullable<System.DateTime> stime { get; set; }
        public Nullable<System.DateTime> sre { get; set; }
    }
}
